version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  library.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

